project/src/java/addhandler/SubCategoryMB.java
package addhandler;

import dao.AddDao;
import dao.ListDao;
import entity.Category;
import entity.SubCategory;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;

@ManagedBean(name = "obj2") 
@SessionScoped
public class SubCategoryMB 
{
    SubCategory subcat = new SubCategory();
    Category category = new Category();
    String catname;
    List<Category> listcat;

    
    // Setter & Getter
    public List<Category> getListcat() {
        return listcat;
    }

    public void setListcat(List<Category> listcat) {
        this.listcat = listcat;
    }

    public SubCategory getSubcat() {
        return subcat;
    }

    public void setSubcat(SubCategory sbucat) {
        this.subcat = subcat;
    }

    public String getCatname() {
        return catname;
    }

    public void setCatname(String catname) {
        this.catname = catname;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }
    
    // Setter & Getter close
    
    
    
    
    
    
    
    public String addSubCategory()
    {
        listcat = new ListDao().catListByName(catname);
        
        category.setCatId(listcat.get(0).getCatId());
        
        subcat.setCategory(category);
        subcat.setSubCatName(subcat.getSubCatName());
        subcat.setSubCatDesc(subcat.getSubCatDesc());
        
        boolean status = new AddDao().addSubCategory(subcat);
        if(status)
        { 
            FacesContext.getCurrentInstance().addMessage(null, new 
            FacesMessage(FacesMessage.SEVERITY_INFO, "Data Saved Successfully", ""));
        } 
        else
        { 
            FacesContext.getCurrentInstance().addMessage(null, new 
                         FacesMessage(FacesMessage.SEVERITY_WARN, "Data not Saved", ""));
        } 
        return null;
    }
    
    
    public List<SelectItem> getCategoryName()
    {
        List<SelectItem> catname = new ListDao().catList();
        
        return catname;
    }
}

project/web/admin/addcategory.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"> 
    
    
    
    
    <h:head>
        <title>ProgGyan ONLINE</title> 
    </h:head> 
    
    <h:body> 
        <f:view> 
            <h:form>  
                <p:messages id="msg" closable="true" showDetail="true"/>
                <p:panelGrid columns="2"> 
                    <h:outputLabel value="Category Name"/> 
                    <h:inputText value="#{obj.category.catName}"/> 
                    
                    <h:outputLabel value="Category Description"/> 
                    <h:inputTextarea value="#{obj.category.catDesc}"/> 
                    
                    <p:commandButton update="msg" value="Save" action="#{obj.addCategory()}"/> 
                </p:panelGrid> 
            </h:form> 
        </f:view> 
    </h:body> 
</html> 

project/web/admin/addsubcat.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"> 
    
    
    
    
    <h:head>
        <title>ProgGyan ONLINE</title> 
    </h:head> 
    
    <h:body> 
        <f:view> 
            <h:form>  
                <p:messages id="msg" closable="true" showDetail="true"/>
                <p:panelGrid columns="2"> 
                    <h:outputLabel value="Select Category Name"/> 
                    <p:selectOneMenu value="#{obj2.catname}"> 
                        <f:selectItem itemLabel="Select Category Name" itemValue="" />
                        <f:selectItems value="#{obj2.categoryName}" /> 
                    </p:selectOneMenu> 
                    
                    <h:outputLabel value="Sub Category Name"/> 
                    <h:inputTextarea value="#{obj2.subcat.subCatName}"/> 
                    
                    <h:outputLabel value="Sub Category Description"/> 
                    <h:inputTextarea value="#{obj2.subcat.subCatDesc}"/> 
                    
                    <p:commandButton update="msg" value="Save" action="#{obj2.addSubCategory()}"/> 
                </p:panelGrid> 
            </h:form> 
        </f:view> 
    </h:body> 
</html> 